export function createEntity() {

}
// TODO: make this autogenerated and improve the api...
export type HookFunction = () => void;
export type HookPoints = 'corru_loaded' | 'corru_leaving' | 'entity_created' | 'entity_deleted';

class CorruModding {
	private hooks: { [eventName in HookPoints]: HookFunction[] } = {
		corru_leaving: [],
		corru_loaded: [],
		entity_created: [],
		entity_deleted: [],
	};

	public registerHook(eventName: HookPoints, hookFunction: HookFunction): void {
		this.hooks[eventName].push(hookFunction);
	}

	public triggerHooks(eventName: HookPoints): void {
		const eventHooks = this.hooks[eventName];
		if (eventHooks)
			eventHooks.forEach(h => h());
	}
}

export const corruModding = new CorruModding();

corruModding.triggerHooks('corru_leaving');
